version: '3.8'

services:
  # Main Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=geominer
      - POSTGRES_PASSWORD=geominer_password
      - POSTGRES_DB=geominer_ai_miner
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - SECRET_KEY=dev-secret-key-not-for-production
      - DOMAIN=geo-miner.com
      - API_DOMAIN=api.geo-miner.com
      - FRONTEND_URL=https://geo-miner.com
      - API_URL=https://api.geo-miner.com
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app:cached
    networks:
      - geominer-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # PostgreSQL Database with PostGIS
  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=geominer
      - POSTGRES_PASSWORD=geominer_password
      - POSTGRES_DB=geominer_ai_miner
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geominer-network

  # Redis for Caching and Job Queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - geominer-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - geominer-network
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  geominer-network:
    driver: bridge 