version: '3.8'
services:
  db:
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_DB: geovision_ai_miner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./geovision-ai-miner-server
    env_file:
      - ./geovision-ai-miner-server/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./geovision-ai-miner-server/uploaded_datasets:/app/uploaded_datasets
  frontend:
    build: ./geovision-ai-miner-client
    env_file:
      - ./geovision-ai-miner-client/.env
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  pgdata: 